apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: {{ .Release.Name }}
rules:
    - apiGroups:
          - ""
      resources:
          - pods
          - services
          - endpoints
          - events
          - configmaps
          - secrets
      verbs:
          - '*'
    - apiGroups:
          - ""
      resources:
          - namespaces
      verbs:
          - get
    - apiGroups:
          - apps
      resources:
          - statefulsets
          - deployments
      verbs:
          - '*'
    - apiGroups:
          - policy
      resources:
          - poddisruptionbudgets
      verbs:
          - '*'
    - apiGroups:
          - cloud.atomix.io
          - storage.cloud.atomix.io
      resources:
          - '*'
      verbs:
          - '*'