apiVersion: storage.cloud.atomix.io/v1beta1
kind: RedisStorageClass
metadata:
  name: redis-storage-node
  labels:
    app: redis-storage-node
spec:
  proxy:
      image: atomix/redis-storage-node:latest
      imagePullPolicy: IfNotPresent
  backend:
    image: redis:latest
    imagePullPolicy: IfNotPresent
    replicas: 1
