apiVersion: storage.cloud.atomix.io/v1beta1
kind: RedisStorage
metadata:
  name: redis-storage
  labels:
    app: redis-storage
spec:
  proxy:
      image: atomix/redis-storage:latest
      imagePullPolicy: IfNotPresent
  backend:
      metadata:
        name: redis-storage
        labels:
          app: redis-storage
      image: redis:latest
      replicas: 1
      livenessProbe:
        tcpSocket:
          port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
      readinessProbe:
        exec:
          command:
            - redis-cli
          initialDelaySeconds: 5
          periodSeconds: 5