apiVersion: v2
name: redis-storage-controller
description: Redis Storage Controller
kubeVersion: ">=1.12.0"
type: application
version: 0.1.0
appVersion: 1.0
keywords:
  - atomix
home: https://atomix.io
maintainers:
  - name: adib
    email: adib@opennetworking.org
  - name: kuujo
    email: jordan@opennetworking.org
